name: Release Spring Boot Native (AMD64 + ARM64)

on:
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        arch: [ amd64, arm64 ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Write tag version to file
        run: |
          echo "${{ github.ref_name }}" > app.version.txt
          cat app.version.txt

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
          components: 'native-image'
          native-image-musl: 'true'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'

      - name: Build Native Image (${{ matrix.arch }})
        if: matrix.arch == 'amd64'
        run: |
          mvn -B -Pnative \
              -Dnative.image.cache=true \
              -Dnative-image.parallelism=4 \
              -DskipTests \
              package
          cd target
          chmod +x atv
          mv atv atv-amd64
          tar zcvf atv-amd64.tgz atv-amd64

      - name: Build ARM64 Native Image (Cross-Compilation)
        if: matrix.arch == 'arm64'
        run: |
          sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu libstdc++-12-dev-arm64-cross
          mvn -B -Pnative \
              -Dnative.image.cache=true \
              -Dnative-image.parallelism=4 \
              -DskipTests \
              -Dnative.buildtools.build.target=linux-aarch_64 \
              package
          cd target
          chmod +x atv
          mv atv atv-arm64
          tar zcvf atv-arm64.tgz atv-arm64

      - name: Upload Artifact (${{ matrix.arch }})
        uses: actions/upload-artifact@v3
        with:
          name: atv-${{ matrix.arch }}.tgz
          path: target/atv-${{ matrix.arch }}.tgz

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/atv-amd64.tgz
            artifacts/atv-arm64.tgz

      - name: Send version notification
        env:
          API_URL: ${{ secrets.VERSION_API }}
        if: ${{ env.API_URL != '' }}
        run: |
          curl -s "${{ env.API_URL }}?type=app&version=${{ github.ref_name }}"