name: Release Native Binary

on:
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        arch: [ amd64, arm64 ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
          native-image-musl: 'true'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install ARM64 Toolchain
        if: matrix.arch == 'arm64'
        run: |
          sudo apt-get update && sudo apt-get install -y \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu \
            libstdc++6-arm64-cross \
            libz-dev-arm64-cross

      - name: Build Native Image
        run: |
          mvn -B -Pnative \
            -Dnative.image.cache=true \
            -Dnative.buildtools.build.target=${{ matrix.arch == 'arm64' && 'linux-aarch64' || 'linux-x86_64' }} \
            -Dnative-image.parallelism=4 \
            -DskipTests \
            package

          cd target
          mv atv atv-${{ matrix.arch }}
          strip --strip-debug atv-${{ matrix.arch }}
          tar zcvf atv-${{ matrix.arch }}.tgz atv-${{ matrix.arch }}

      - name: Test ARM64 Binary (QEMU)
        if: matrix.arch == 'arm64'
        run: |
          sudo apt-get install -y qemu-user-static
          qemu-aarch64-static ./target/atv-arm64 --version || true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}
          path: target/atv-${{ matrix.arch }}.tgz

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/amd64/atv-amd64.tgz
            artifacts/arm64/atv-arm64.tgz